name: greengrass-lite-snap
version: '1.0'
summary: SystemD container with AWS Greengrass Lite via docker-compose
description: Provides systemd container with AWS Greengrass Lite definition via docker-compose pattern
base: core22

grade: devel
confinement: strict

slots:
  docker-compose:
    interface: content
    content: docker-compose
    source:
      read:
        - $SNAP/docker-compose/${CRAFT_PROJECT_NAME}
  docker-volumes:
    interface: content
    content: docker-volumes
    source:
      write:
        - $SNAP_DATA/docker-volumes/${CRAFT_PROJECT_NAME}

parts:
  docker-compose:
    plugin: dump
    source: ./docker-compose
    organize:
      '*': docker-compose/${CRAFT_PROJECT_NAME}/
