name: systemd-compose-snap
version: '1.0'
summary: SystemD container with AWS Greengrass Lite via docker-compose
description: Provides systemd container with AWS Greengrass Lite definition via docker-compose pattern
base: core22

grade: devel
confinement: strict

slots:
  docker-compose:
    interface: content
    content: docker-compose
    source:
      read:
        - $SNAP/docker-compose/${CRAFT_PROJECT_NAME}
  docker-volumes:
    interface: content
    content: docker-volumes
    source:
      write:
        - $SNAP_DATA/docker-volumes/${CRAFT_PROJECT_NAME}

hooks:
  configure:
    plugs: [snapd-control]

apps:
  info:
    command: bin/compose-info
  
  daemon:
    command: bin/start-container
    daemon: simple
    restart-condition: always
    plugs: [docker, network]

parts:
  docker-compose:
    plugin: dump
    source: ./docker-compose
    organize:
      '*': docker-compose/${CRAFT_PROJECT_NAME}/
  
  scripts:
    plugin: dump
    source: .
    organize:
      compose-info: bin/compose-info
      start-container: bin/start-container
    stage:
      - bin/compose-info
      - bin/start-container
  
  hooks:
    plugin: dump
    source: hooks
    organize:
      '*': meta/hooks/
