name: systemd-compose-snap
version: '1.0'
summary: SystemD container with AWS Greengrass Lite via docker-compose
description: Provides systemd container with AWS Greengrass Lite definition via docker-compose pattern
base: core22

grade: devel
confinement: strict

slots:
  docker-compose:
    interface: content
    content: docker-compose
    source:
      read:
        - $SNAP/docker-compose/${CRAFT_PROJECT_NAME}
  docker-volumes:
    interface: content
    content: docker-volumes
    source:
      write:
        - $SNAP_DATA/docker-volumes/${CRAFT_PROJECT_NAME}

apps:
  info:
    command: bin/compose-info

parts:
  docker-compose:
    plugin: dump
    source: ./docker-compose
    organize:
      '*': docker-compose/${CRAFT_PROJECT_NAME}/
  
  scripts:
    plugin: dump
    source: .
    organize:
      compose-info: bin/compose-info
    stage:
      - bin/compose-info
