version: '3.8'

services:
  systemd-container:
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    container_name: greengrass-lite
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - ${SNAP_DATA}/docker-volumes/${SNAPCRAFT_PROJECT_NAME}/config:/etc/greengrass:rw
      - ${SNAP_DATA}/docker-volumes/${SNAPCRAFT_PROJECT_NAME}/components:/opt/aws/iot/greengrass/components:rw
      - ${SNAP_DATA}/docker-volumes/${SNAPCRAFT_PROJECT_NAME}/lib:/var/lib/greengrass:rw
      - systemd-data:/data
    restart: unless-stopped
    tty: true
    stdin_open: true

volumes:
  systemd-data:
    driver: local
